name: crcl-dispatch

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [CRCL_Run]
jobs:
  build:
    name: Run crcl.py
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: crcl_enviro
    steps:
      - name: client-payload
        run: |
          echo "$env:GITHUB_EVENT_PATH"
          echo "${{ github.event.client_payload.event_type }}"
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python crcl-r.py